package globals

const KB = 1024
const MB = 1024 * 1024
const GB = 1024 * 1024 * 1024
const MESSAGE_BUFFER_SIZE = 256
const RAND_STRING_SIZE = 16

var BIN_DIR string
var COLON_DELIMITER = []byte(":")
var FILE_SIZE_TYPES = []string{"KB", "MB", "GB"}
var ROOT_DIR string

var END_TRANSFER_MARKER = []byte("<END_TRANSFER>")
var HASHES_TRANSFER_PREFIX = []byte("<TRANSFER_HASHES:")
var LOG_TRANSFER_PREFIX = []byte("<TRANSFER_LOG:")
var LOOT_TRANSFER_PREFIX = []byte("<TRANSFER_LOOT:")
var PROCESSING_COMPLETE = []byte("<PROCESSING_COMPLETE>")
var RULESET_TRANSFER_PREFIX = []byte("<TRANSFER_RULESET:")
var START_TRANSFER_PREFIX = []byte("<START_TRANSFER:")
var TRANSFER_INITIATED_MARKER = []byte("<TRANSFER_INITIATED>")
var TRANSFER_REQUEST_PREFIX = []byte("<TRANSFER_REQUEST:")
var TRANSFER_SUFFIX = []byte(">")
