package globals

const KB = 1024
const MB = 1024 * 1024
const GB = 1024 * 1024 * 1024
const MESSAGE_BUFFER_SIZE = 256
const OS_RESERVED_SPACE = 10 * GB
const RAND_STRING_SIZE = 16

var COLON_DELIMITER = []byte(":")
var HASHES_TRANSFER_PREFIX = []byte("<TRANSFER_HASHES:")
var RULESET_TRANSFER_PREFIX = []byte("<TRANSFER_RULESET:")
var TRANSFER_REQUEST_MARKER = []byte("<TRANSFER_REQUEST>")
var START_TRANSFER_PREFIX = []byte("<START_TRANSFER:")
var LOOT_TRANSFER_PREFIX = []byte("<TRANSFER_LOOT:")
var LOG_TRANSFER_PREFIX = []byte("<TRANSFER_LOG:")
var TRANSFER_SUFFIX = []byte(">")
var END_TRANSFER_MARKER = []byte("<END_TRANSFER>")
var PROCESSING_COMPLETE = []byte("<PROCESSING_COMPLETE>")
var FILE_SIZE_TYPES = []string{"kb", "mb", "gb"}
