local_config:
  region: "us-east-1"
  listener_port: 6969
  number_instances: 1
  load_dir: ""
  hash_file_path: ""
  ruleset_path: ""
  max_size_range: 15.0
  log_path: "KloudKraken.log"

client_config:
  region: "us-east-1"
  max_file_size: "1GB"
  cracking_mode: "0"
  hash_type: "1000"
  apply_optimization: true
  workload: "3"
  char_set1: ""
  char_set2: ""
  char_set3: ""
  char_set4: ""
  hash_mask: ""
  max_transfers: 3
  log_mode: "local"
  log_path: "KloudKraken.log"
