local_config:
  region: "us-east-1"
  listener_port: 6969
  number_instances: 1
  load_dir: "/home/thebugfather/Documents/project_testing/project_data"
  hash_file_path: "/home/thebugfather/Documents/project_testing/test-hashes"
  ruleset_path: ""
  max_merging_size: "500MB"
  max_size_range: 15.0
  log_path: "KloudKraken.log"
  local_testing: true

client_config:
  region: "us-east-1"
  max_file_size: "16GB"
  cracking_mode: "0"
  hash_type: "1700"
  apply_optimization: false
  workload: "3"
  char_set1: ""
  char_set2: ""
  char_set3: ""
  char_set4: ""
  hash_mask: ""
  max_transfers: 3
  log_mode: "local"
  log_path: "/tmp/KloudKraken.log"
