local_config:
  account_id: "123456789123"
  bucket_name: "test-bucket"
  hash_file_path: "/home/thebugfather/Documents/project_testing/test-hashes"
  iam_username: "test-user"
  instance_type: "p4d.24xlarge"
  listener_port: 6969
  load_dir: "/home/thebugfather/Documents/project_testing/project_data"
  local_testing: true
  log_path: "./bin/KloudKraken.log"
  max_merging_size: "750MB"
  max_size_range: 15.0
  number_instances: 1
  region: "us-east-1"
  ruleset_path: ""
  security_group_ids: []
  security_groups: []
  subnet_id: ""

client_config:
  apply_optimization: true
  char_set1: ""
  char_set2: ""
  char_set3: ""
  char_set4: ""
  cracking_mode: "0"
  hash_mask: ""
  hash_type: "1700"
  log_mode: "both"
  log_path: "KloudKraken.log"
  max_file_size: "2GB"
  max_transfers: 3
  region: "us-east-1"
  workload: "4"
