client_config:
  apply_optimization: true
  char_set1: ""
  char_set2: ""
  char_set3: ""
  char_set4: ""
  cracking_mode: "0"
  hash_mask: ""
  hash_type: "1700"
  log_mode: "both"
  max_file_size: "1GB"
  max_transfers: 2
  region: "us-east-2"
  workload: "4"

local_config:
  cidr_block: "192.168.0.0/25"
  hash_file_path: "/home/thebugfather/Documents/project_testing/test-hashes"
  iam_username: "TheBugFather"
  instance_type: "g6f.xlarge"
  listener_port: 7003
  load_dir: "/home/thebugfather/Documents/project_testing/project_data"
  local_testing: false
  max_merging_size: "300MB"
  max_size_range: 15.0
  number_instances: 1
  region: "us-east-2"
  ruleset_path: ""
