local_config:
  region: "us-east-1"
  listener_port: 6969
  number_instances: 1
  load_dir: ""
  hash_file_path: ""
  ruleset_path: ""
  log_path: "KloudKraken.log"

client_config:
  region: "us-east-1"
  max_file_size: "1GB"
  cracking_mode: "0"
  hash_type: "1000"
  max_transfers: 3
  log_mode: "local"
  log_path: "KloudKraken.log"
